//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PokemonGoScannerDbEntities1 : DbContext
    {
        public PokemonGoScannerDbEntities1()
            : base("name=PokemonGoScannerDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<LocationSubscription> LocationSubscriptions { get; set; }
        public virtual DbSet<Scanner> Scanners { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
